# Mane of your workflow
name: My test workflow

# Define the trigger event(s)
on: [push]

# Job run in parallel by default, each runs steps in sequence
jobs:
    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Sey hello
              run: echo "Hello, GitHub actions"
            
    # Job to build and test our C code
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
        
            # Use github.com/actions/checkout to check out this repo
            - name: Check out this repo
              uses: actions/checkout@v3
              
            # Install necessary packages
            - name: Install dependencies
              run: sudo apt install -y build-essential python3
              
            # See where we are in the VW
            - run: pwd
            
            # Run our test
            - name: Run test
              run: python3 test.py
              